FROM mongo
RUN apt-get update && apt-get install -y curl build-essential libssl-dev
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash
RUN apt-get install -y nodejs
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
