version: "3"

volumes:
    mongo:
    redis:

services:
    # The app is going to run on the host machine's port 4444 in development
    nginx:
        restart: always
        depends_on:
            - flask
            - gatsby
        build:
            dockerfile: Dockerfile.dev
            context: ./containers/nginx
        ports:
            - "4444:80"

    # The main content pages are in this container
    gatsby:
        build:
            dockerfile: Dockerfile.dev
            context: ./containers/gatsby
        # It might eventually pull data from Express, so wait for that container to boot.
        depends_on:
            - flask
        volumes:
            - /app/node_modules
            - ./containers/gatsby:/app
        environment:
            - NODE_ENV=development
            - GATSBY_WEBPACK_PUBLICPATH=/
        working_dir: /app
        command: ./entrypoint.sh

    flask:
        build:
            dockerfile: Dockerfile
            context: ./containers/flask
        depends_on:
            - mongo
        volumes:
            - ./containers/flask:/app
        env_file: .env/flask

    mongo:
        build:
            dockerfile: Dockerfile
            context: ./containers/mongo
        volumes:
            - mongo:/data/db

    # TODO: it might be okay to remove this, since express.js is gone.
    redis:
        image: "redis:latest"
        volumes:
            - redis:/data
