version: "3"

volumes:
    mongo:
    redis:
    postgres:

services:
    # The app is going to run on the host machine's port 4444 in development
    nginx:
        restart: always
        depends_on:
            - flask
            - gatsby
        build:
            dockerfile: Dockerfile.dev
            context: ./containers/nginx
        ports:
            - "4444:80"

    # The main content pages are in this container
    gatsby:
        build:
            dockerfile: Dockerfile.dev
            context: ./containers/gatsby
        depends_on:
            - flask
        volumes:
            - /app/node_modules
            - ./containers/gatsby:/app
        environment:
            - NODE_ENV=development
            - GATSBY_WEBPACK_PUBLICPATH=/
        working_dir: /app
        command: ./entrypoint.sh

    flask:
        build:
            dockerfile: Dockerfile
            context: ./containers/flask
        depends_on:
            - mongo
        volumes:
            - ./containers/flask:/app
        env_file: .env/flask

    django:
        build:
            dockerfile: dev.Dockerfile
            context: ./containers/django
        depends_on:
            - postgres
        volumes:
            - ./containers/django:/app
        env_file: .env/django
        command: python manage.py runserver 0.0.0.0:8000

    postgres:
        build:
            dockerfile: Dockerfile
            context: ./containers/postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file: .env/postgres

    mongo:
        build:
            dockerfile: Dockerfile
            context: ./containers/mongo
        volumes:
            - mongo:/data/db

    redis:
        image: "redis:latest"
        volumes:
            - redis:/data
