version: "3"

volumes:
    mongo:
    redis:

services:
    nginx:
        restart: always
        depends_on:
            - flask
            - gatsby
        build:
            dockerfile: Dockerfile
            context: ./containers/nginx
        ports:
            # There is an nginx install on the host machine temporarily
            - "4444:80"
            # - "443:443"
        # volumes:
        #     - ./data/certbot/conf:/etc/letsencrypt
        #     - ./data/certbot/www:/var/www/certbot
        # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    gatsby:
        build:
            dockerfile: Dockerfile
            context: ./containers/gatsby
        depends_on:
            - flask
        environment:
            - NODE_ENV=production
            - GATSBY_WEBPACK_PUBLICPATH=/
        working_dir: /app

    flask:
        build:
            dockerfile: Dockerfile
            context: ./containers/flask
        depends_on:
            - mongo
        volumes:
            - ./containers/flask:/app
        env_file: .env/flask

    mongo:
        build:
            dockerfile: Dockerfile
            context: ./containers/mongo
        volumes:
            - mongo:/data/db

    # TODO: it might be okay to remove this if flask won't use it.
    redis:
        image: "redis:latest"
        volumes:
            - redis:/data

    # This obtains the Let's Encrypt certificates
    # certbot:
    #     image: certbot/certbot
    # volumes:
    #     - ./data/certbot/conf:/etc/letsencrypt
    #     - ./data/certbot/www:/var/www/certbot
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
