/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ToolsRouteImport } from "./routes/tools";
import { Route as SRouteImport } from "./routes/s";
import { Route as PuzzlesRouteImport } from "./routes/puzzles";
import { Route as LearnRouteImport } from "./routes/learn";
import { Route as JobsRouteImport } from "./routes/jobs";
import { Route as ForumRouteImport } from "./routes/forum";
import { Route as EventsRouteImport } from "./routes/events";
import { Route as DiscountsRouteImport } from "./routes/discounts";
import { Route as CreditsRouteImport } from "./routes/credits";
import { Route as ContactRouteImport } from "./routes/contact";
import { Route as CodewarsRouteImport } from "./routes/codewars";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";

const ToolsRoute = ToolsRouteImport.update({
  id: "/tools",
  path: "/tools",
  getParentRoute: () => rootRouteImport,
} as any);
const SRoute = SRouteImport.update({
  id: "/s",
  path: "/s",
  getParentRoute: () => rootRouteImport,
} as any);
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: "/puzzles",
  path: "/puzzles",
  getParentRoute: () => rootRouteImport,
} as any);
const LearnRoute = LearnRouteImport.update({
  id: "/learn",
  path: "/learn",
  getParentRoute: () => rootRouteImport,
} as any);
const JobsRoute = JobsRouteImport.update({
  id: "/jobs",
  path: "/jobs",
  getParentRoute: () => rootRouteImport,
} as any);
const ForumRoute = ForumRouteImport.update({
  id: "/forum",
  path: "/forum",
  getParentRoute: () => rootRouteImport,
} as any);
const EventsRoute = EventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => rootRouteImport,
} as any);
const DiscountsRoute = DiscountsRouteImport.update({
  id: "/discounts",
  path: "/discounts",
  getParentRoute: () => rootRouteImport,
} as any);
const CreditsRoute = CreditsRouteImport.update({
  id: "/credits",
  path: "/credits",
  getParentRoute: () => rootRouteImport,
} as any);
const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
} as any);
const CodewarsRoute = CodewarsRouteImport.update({
  id: "/codewars",
  path: "/codewars",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/codewars": typeof CodewarsRoute;
  "/contact": typeof ContactRoute;
  "/credits": typeof CreditsRoute;
  "/discounts": typeof DiscountsRoute;
  "/events": typeof EventsRoute;
  "/forum": typeof ForumRoute;
  "/jobs": typeof JobsRoute;
  "/learn": typeof LearnRoute;
  "/puzzles": typeof PuzzlesRoute;
  "/s": typeof SRoute;
  "/tools": typeof ToolsRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/codewars": typeof CodewarsRoute;
  "/contact": typeof ContactRoute;
  "/credits": typeof CreditsRoute;
  "/discounts": typeof DiscountsRoute;
  "/events": typeof EventsRoute;
  "/forum": typeof ForumRoute;
  "/jobs": typeof JobsRoute;
  "/learn": typeof LearnRoute;
  "/puzzles": typeof PuzzlesRoute;
  "/s": typeof SRoute;
  "/tools": typeof ToolsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/codewars": typeof CodewarsRoute;
  "/contact": typeof ContactRoute;
  "/credits": typeof CreditsRoute;
  "/discounts": typeof DiscountsRoute;
  "/events": typeof EventsRoute;
  "/forum": typeof ForumRoute;
  "/jobs": typeof JobsRoute;
  "/learn": typeof LearnRoute;
  "/puzzles": typeof PuzzlesRoute;
  "/s": typeof SRoute;
  "/tools": typeof ToolsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/codewars"
    | "/contact"
    | "/credits"
    | "/discounts"
    | "/events"
    | "/forum"
    | "/jobs"
    | "/learn"
    | "/puzzles"
    | "/s"
    | "/tools";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/codewars"
    | "/contact"
    | "/credits"
    | "/discounts"
    | "/events"
    | "/forum"
    | "/jobs"
    | "/learn"
    | "/puzzles"
    | "/s"
    | "/tools";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/codewars"
    | "/contact"
    | "/credits"
    | "/discounts"
    | "/events"
    | "/forum"
    | "/jobs"
    | "/learn"
    | "/puzzles"
    | "/s"
    | "/tools";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  CodewarsRoute: typeof CodewarsRoute;
  ContactRoute: typeof ContactRoute;
  CreditsRoute: typeof CreditsRoute;
  DiscountsRoute: typeof DiscountsRoute;
  EventsRoute: typeof EventsRoute;
  ForumRoute: typeof ForumRoute;
  JobsRoute: typeof JobsRoute;
  LearnRoute: typeof LearnRoute;
  PuzzlesRoute: typeof PuzzlesRoute;
  SRoute: typeof SRoute;
  ToolsRoute: typeof ToolsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/tools": {
      id: "/tools";
      path: "/tools";
      fullPath: "/tools";
      preLoaderRoute: typeof ToolsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/s": {
      id: "/s";
      path: "/s";
      fullPath: "/s";
      preLoaderRoute: typeof SRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/puzzles": {
      id: "/puzzles";
      path: "/puzzles";
      fullPath: "/puzzles";
      preLoaderRoute: typeof PuzzlesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/learn": {
      id: "/learn";
      path: "/learn";
      fullPath: "/learn";
      preLoaderRoute: typeof LearnRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/jobs": {
      id: "/jobs";
      path: "/jobs";
      fullPath: "/jobs";
      preLoaderRoute: typeof JobsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/forum": {
      id: "/forum";
      path: "/forum";
      fullPath: "/forum";
      preLoaderRoute: typeof ForumRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/events": {
      id: "/events";
      path: "/events";
      fullPath: "/events";
      preLoaderRoute: typeof EventsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/discounts": {
      id: "/discounts";
      path: "/discounts";
      fullPath: "/discounts";
      preLoaderRoute: typeof DiscountsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/credits": {
      id: "/credits";
      path: "/credits";
      fullPath: "/credits";
      preLoaderRoute: typeof CreditsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/codewars": {
      id: "/codewars";
      path: "/codewars";
      fullPath: "/codewars";
      preLoaderRoute: typeof CodewarsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CodewarsRoute: CodewarsRoute,
  ContactRoute: ContactRoute,
  CreditsRoute: CreditsRoute,
  DiscountsRoute: DiscountsRoute,
  EventsRoute: EventsRoute,
  ForumRoute: ForumRoute,
  JobsRoute: JobsRoute,
  LearnRoute: LearnRoute,
  PuzzlesRoute: PuzzlesRoute,
  SRoute: SRoute,
  ToolsRoute: ToolsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
