FROM node:12-alpine

# see https://dev.to/stoutlabs/my-docker-setup-for-gatsbyjs-and-nextjs-5gao
RUN \
    apk add --no-cache python make g++ && \
    apk add vips-dev fftw-dev --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community --repository http://dl-3.alpinelinux.org/alpine/edge/main && \
    rm -fR /var/cache/apk/*

WORKDIR /app
RUN npm install -g gatsby-cli
# RUN gatsby telemetry --disable
COPY ./package.json ./
RUN npm install
COPY . .
EXPOSE 8000
CMD ["gatsby", "develop"]
