FROM node:12-alpine as builder
RUN apk update && apk add build-base autoconf automake libtool pkgconfig nasm
WORKDIR /app
COPY ./package*.json ./
ENV GATSBY_TELEMETRY_DISABLED=1
RUN mkdir node_modules && npm install

# Get a clean image with gatsby-cli and the pre-built node modules
FROM node:12-alpine
ENV GATSBY_TELEMETRY_DISABLED=1
RUN npm install --global gatsby-cli && gatsby telemetry --disable && mkdir /save
COPY --from=builder /app/node_modules /save/node_modules
